name: Jekyll site CI

on:
  push:
    branches: [ source ]

jobs:
  build:
    name: Build and deploy website
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.4.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Set up environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Replace variables
        run: |
          bash ./.github/workflows/replace_var.sh ENV_CLIENT_ID ${CLIENT_ID} ./give_feedback/index.html
          bash ./.github/workflows/replace_var.sh ENV_CLIENT_SECRET ${CLIENT_SECRET} ./give_feedback/index.html

      - name: Build website
        run: |
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Push to master branch
        run: |
          bash ./.github/workflows/push.sh
